### ISSUE TITLE
81 Tiles 2

### ISSUE THREAD

**Issue by Mengkubaucarwash** [kurema/CitiesSkylinesModsRepoForEpicUsers#1]
Hi 

I have very little experience.. With the new update I am unable to use 81 tiles 2. Hope you can post the new update.. Many thanks..

**Comment by kurema** [comment]
New version [here](https://github.com/kurema/CitiesSkylinesModsRepoForEpicUsers/releases/tag/24-May-2023). It looks like it's working with latest update.
You have to delete [Font Selector](https://steamcommunity.com/workshop/filedetails/?id=412149127) if you use it. And some Mods like [TM:PE](https://steamcommunity.com/sharedfiles/filedetails/?id=1637663252) shows warnings. I think you should wait some days just in case.

**Comment by Mengkubaucarwash** [comment]
Thanks mate
