### ISSUE TITLE
Updated Mods 1.17

### ISSUE THREAD

**Issue by TheZiro** [kurema/CitiesSkylinesModsRepoForEpicUsers#4]
`Picker` [Releases](https://github.com/Quboid/Picker/releases/tag/v4.0.1b)

`Move It` [Releases](https://github.com/Quboid/CS-MoveIt/releases/tag/v2.10.7)

**Comment by kurema** [comment]
Thanks. But they are already in the list of README.md.
![image](https://github.com/kurema/CitiesSkylinesModsRepoForEpicUsers/assets/10556974/546ef9af-5524-4355-81e1-6ce8636cfd7c)
